const columnOrder = [
  "slNo",
  "customerName",
  "jobId",
  "sellingPrice",
  "costPrice",
  "jobDate",
  "category",
  "jobParticulars",
  "jobReference",
  "boeSbNo",
  "boeSbDate",
  "arrivalDate",
  "dutyPaidDate",
  "clearanceDate",
  "action",
  "tentativeClosureDate",
  "closedDate",
  "tat",
  "remarks",
  "billingStatus",
  "apekshaInvoiceNo",
  "invoiceDate",
  "dateOfCourier",
  "courierTrackingNo",
  "paymentStatus",
  "updatedBy",
  "updatedAt",
  "jobControls",
];

export default columnOrder;
